width: 800
height: 600
linter: "mdast-lint"
lint_options:
  maximum-line-length: false
drawer:
  responsive: false
menu:
  visible: true
shortcuts:
  "g g": "PageTop"
  "shift+g": "PageBottom"
  i: ""
  m: ""
  command+q: "QuitApp"
  command+w: "QuitApp"
file_ext:
  markdown:
    - "md"
    - "markdown"
    - "mkd"
  html:
    - "html"
voice:
  enabled: false
  source: C:\Users\toshi\AppData\Roaming\npm\node_modules\shiba\build\voices\bow.mp3

